name: Update heartbeat.json

on:
  # Every 10 minutes — adjust as you like
  schedule:
    - cron: '*/10 * * * *'
  # Allow manual runs
  workflow_dispatch:

jobs:
  bump:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Write fresh timestamp
        run: |
          node - <<'EOF'
          const fs = require('fs');
          fs.writeFileSync(
            'heartbeat.json',
            JSON.stringify({ timestamp: Date.now() })
          );
          console.log('heartbeat.json updated');
          EOF

      - name: Commit & push
        uses: EndBug/add-and-commit@v9
        with:
          message: 'chore: bump heartbeat 🫀'
          add: 'heartbeat.json'
          default_author: github_actions
